version: '3.4'

services:
  catalogdb:
    image: mongo

  flymateapi:
    image: ${DOCKER_REGISTRY-}flymateapi
    build:
      context: .
      dockerfile: API\Dockerfile

  mongo-express:
    image: mongo-express