name: Build and Test 

on:
  push:
    branches:
      - develop
    paths:
      - "**.cs"
      - ".editorconfig"
  pull_request:
    branches:
      - develop
    paths:
      - "**.cs"
      - ".editorconfig"

jobs:
  check-format:
    runs-on: windows-latest

    steps:      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1

      - name: Check out code
        uses: actions/checkout@v2

      - name: NuGet restore
        run: nuget restore FlyMate.sln
        
      - name: Restore dependencies
        run: dotnet restore FlyMate.sln

      - name: Run dotnet format FlyMate.sln
        run: dotnet format --verify-no-changes --no-restore --verbosity diagnostic
      
      - name: Build
        run: dotnet build --no-restore
